Add files via upload

diff --git a/.github/workflows/Qemu-Vortax V 1.9.yml b/.github/workflows/Qemu-Vortax V 1.9.yml
--- a/.github/workflows/Qemu-Vortax V 1.9.yml
+++ b/.github/workflows/Qemu-Vortax V 1.9.yml
@@ -1,4 +1,4 @@
-name: Qemu-Vortax V 1.8
+name: Qemu-Vortax V 1.9
 
 on:
   workflow_dispatch:
@@ -115,44 +115,48 @@ jobs:
         run: |
           CHOICE="${{ github.event.inputs.system_choice }}"
           USER_URL="${{ github.event.inputs.source_url }}"
-          if [ "$BOOT_MODE" = "iso" ]; then
-            declare -A ISO_URLS
-            ISO_URLS["bazite"]="https://download.bazzite.gg/bazzite-stable-live.iso"
-            ISO_URLS["bliss"]="https://dn720203.ca.archive.org/0/items/Bliss-v15.9-x86_64-OFFICIAL-gapps-20240114/Bliss-v15.9-x86_64-OFFICIAL-gapps-20240114.iso"
-            ISO_URLS["cutefish"]="https://netix.dl.sourceforge.net/project/cutefish-ubuntu/ISO/Ubuntu/CutefishOS-22.04.0-YoYo-beta-amd64.iso?viasf=1"
-            ISO_URLS["deepin"]="https://cdimage-cdn77.deepin.com/deepin-cd/25.0.1/amd64/deepin-desktop-community-25.0.1-amd64.iso"
-            ISO_URLS["garuda_mokka"]="https://r2.garudalinux.org/iso/garuda/mokka/251002/garuda-mokka-linux-zen-251002.iso?r2request"
-            ISO_URLS["kali"]="https://kali.download/base-images/kali-2025.3/kali-linux-2025.3-live-amd64.iso"
-            ISO_URLS["manjaro"]="https://download.manjaro.org/gnome/25.0.10/manjaro-gnome-25.0.10-251013-linux612.iso"
-            ISO_URLS["mint"]="https://pub.linuxmint.io/stable/22.2/linuxmint-22.2-cinnamon-64bit.iso"
-            ISO_URLS["pear"]="https://www.mediafire.com/file/7ztcyqd2ggiv58p/pearOS-NiceC0re-2025.11-x86_64.iso"
-            ISO_URLS["pop_os"]="https://iso.pop-os.org/22.04/amd64/intel/58/pop-os_22.04_amd64_intel_58.iso"
-            ISO_URLS["ubuntu"]="https://releases.ubuntu.com/25.10/ubuntu-25.10-desktop-amd64.iso"
-          else
-            declare -A QCOW2_URLS
-            QCOW2_URLS["centos_qcow2"]="https://cloud.centos.org/centos/10-stream/x86_64/images/CCentOS-Stream-GenericCloud-x86_64-10-latest.x86_64.qcow2"
-            QCOW2_URLS["debian_qcow2"]="https://chuangtzu.ftp.acc.umu.se/images/cloud/bookworm/20251006-2257/debian-12-generic-amd64-20251006-2257.qcow2"
-            QCOW2_URLS["deepin"]="https://www.mediafire.com/file/ozwa2vyxt4hz6wu/dipeen.7z/"
-            QCOW2_URLS["kali"]="https://kali.mirror.garr.it/kali-images/current/kali-linux-2025.3-qemu-amd64.7z"
-            QCOW2_URLS["mint"]="https://www.mediafire.com/file/a4qyactev4kzc0q/mint.7z/"
-            QCOW2_URLS["pop_os"]="https://www.mediafire.com/file/lbrebo479z4fq3g/pop_os.7z/"
-            QCOW2_URLS["bliss"]="https://www.mediafire.com/file/2zuxhk4dtqa735l/bliss.7z/"
-            QCOW2_URLS["win7"]="https://www.mediafire.com/file/p3gkso164vchyvs/win7.7z/"
-          
-          FINAL_URL="$USER_URL"
-          if [[ -z "$FINAL_URL" && -n "$CHOICE" ]]; then
-            FINAL_URL="${ISO_URLS[$CHOICE]}"
-            if [[ -z "$FINAL_URL" ]]; then
+
+          declare -A ISO_URLS
+          ISO_URLS["bazite"]="https://download.bazzite.gg/bazzite-stable-live.iso"
+          ISO_URLS["bliss"]="https://dn720203.ca.archive.org/0/items/Bliss-v15.9-x86_64-OFFICIAL-gapps-20240114/Bliss-v15.9-x86_64-OFFICIAL-gapps-20240114.iso"
+          ISO_URLS["cutefish"]="https://netix.dl.sourceforge.net/project/cutefish-ubuntu/ISO/Ubuntu/CutefishOS-22.04.0-YoYo-beta-amd64.iso?viasf=1"
+          ISO_URLS["deepin"]="https://cdimage-cdn77.deepin.com/deepin-cd/25.0.1/amd64/deepin-desktop-community-25.0.1-amd64.iso"
+          ISO_URLS["garuda_mokka"]="https://r2.garudalinux.org/iso/garuda/mokka/251002/garuda-mokka-linux-zen-251002.iso?r2request"
+          ISO_URLS["kali"]="https://kali.download/base-images/kali-2025.3/kali-linux-2025.3-live-amd64.iso"
+          ISO_URLS["manjaro"]="https://download.manjaro.org/gnome/25.0.10/manjaro-gnome-25.0.10-251013-linux612.iso"
+          ISO_URLS["mint"]="https://pub.linuxmint.io/stable/22.2/linuxmint-22.2-cinnamon-64bit.iso"
+          ISO_URLS["pear"]="https://www.mediafire.com/file/7ztcyqd2ggiv58p/pearOS-NiceC0re-2025.11-x86_64.iso"
+          ISO_URLS["pop_os"]="https://iso.pop-os.org/22.04/amd64/intel/58/pop-os_22.04_amd64_intel_58.iso"
+          ISO_URLS["ubuntu"]="https://releases.ubuntu.com/25.10/ubuntu-25.10-desktop-amd64.iso"
+
+          declare -A QCOW2_URLS
+          QCOW2_URLS["centos_qcow2"]="https://cloud.centos.org/centos/10-stream/x86_64/images/CCentOS-Stream-GenericCloud-x86_64-10-latest.x86_64.qcow2"
+          QCOW2_URLS["debian_qcow2"]="https://chuangtzu.ftp.acc.umu.se/images/cloud/bookworm/20251006-2257/debian-12-generic-amd64-20251006-2257.qcow2"
+          QCOW2_URLS["deepin"]="https://www.mediafire.com/file/ozwa2vyxt4hz6wu/dipeen.7z/"
+          QCOW2_URLS["kali"]="https://kali.mirror.garr.it/kali-images/current/kali-linux-2025.3-qemu-amd64.7z"
+          QCOW2_URLS["mint"]="https://www.mediafire.com/file/a4qyactev4kzc0q/mint.7z/"
+          QCOW2_URLS["pop_os"]="https://www.mediafire.com/file/lbrebo479z4fq3g/pop_os.7z/"
+          QCOW2_URLS["bliss"]="https://www.mediafire.com/file/2zuxhk4dtqa735l/bliss.7z/"
+          QCOW2_URLS["win7"]="https://www.mediafire.com/file/p3gkso164vchyvs/win7.7z/"
+
+          BOOT_MODE="${{ github.event.inputs.boot_mode }}"
+
+          if [[ -n "$USER_URL" ]]; then
+            FINAL_URL="$USER_URL"
+          elif [[ -n "$CHOICE" ]]; then
+            if [[ "$BOOT_MODE" == "iso" && -n "${ISO_URLS[$CHOICE]}" ]]; then
+              FINAL_URL="${ISO_URLS[$CHOICE]}"
+            elif [[ "$BOOT_MODE" == "qcow2" && -n "${QCOW2_URLS[$CHOICE]}" ]]; then
               FINAL_URL="${QCOW2_URLS[$CHOICE]}"
+            else
+              echo "::error::No valid file found for choice '$CHOICE' with boot_mode '$BOOT_MODE'"
+              exit 1
             fi
+          else
+            echo "::error::No system_choice or source_url provided"
+            exit 1
           fi
-
-          if [[ -z "$FINAL_URL" ]]; then
-            FINAL_URL="${ISO_URLS["bliss_gapps"]}"
-          fi
-
-          echo "FINAL_SOURCE_URL=$FINAL_URL" >> $GITHUB_ENV
-
+          
       - name: Configure VM specs
         run: |
           DISK=60
