Add files via upload

diff --git a/.github/workflows/Qemu-Vortax V 1.9.yml b/.github/workflows/Qemu-Vortax V 1.9.yml
--- a/.github/workflows/Qemu-Vortax V 1.9.yml
+++ b/.github/workflows/Qemu-Vortax V 1.9.yml
@@ -110,11 +110,12 @@ jobs:
           chmod +x ~/badown/badown
           sudo touch ~/badown/.badown.tmp
 
-      - name: Determine source URL
+            - name: Determine source URL (Modified Logic)
         id: determine_url
         run: |
           CHOICE="${{ github.event.inputs.system_choice }}"
           USER_URL="${{ github.event.inputs.source_url }}"
+          BOOT_MODE="${{ github.event.inputs.boot_mode }}" # جلب متغير وضع الإقلاع
 
           declare -A ISO_URLS
           ISO_URLS["bazite"]="https://download.bazzite.gg/bazzite-stable-live.iso"
@@ -136,27 +137,29 @@ jobs:
           QCOW2_URLS["kali"]="https://kali.mirror.garr.it/kali-images/current/kali-linux-2025.3-qemu-amd64.7z"
           QCOW2_URLS["mint"]="https://www.mediafire.com/file/a4qyactev4kzc0q/mint.7z/"
           QCOW2_URLS["pop_os"]="https://www.mediafire.com/file/lbrebo479z4fq3g/pop_os.7z/"
-          QCOW2_URLS["blissq"]="https://www.mediafire.com/file/2zuxhk4dtqa735l/bliss.7z/"
+          QCOW2_URLS["bliss"]="https://www.mediafire.com/file/2zuxhk4dtqa735l/bliss.7z/"
           QCOW2_URLS["win7"]="https://www.mediafire.com/file/p3gkso164vchyvs/win7.7z/"
-
-          BOOT_MODE="${{ github.event.inputs.boot_mode }}"
-
-          if [[ -n "$USER_URL" ]]; then
-            FINAL_URL="$USER_URL"
-          elif [[ -n "$CHOICE" ]]; then
-            if [[ "$BOOT_MODE" == "iso" && -n "${ISO_URLS[$CHOICE]}" ]]; then
-              FINAL_URL="${ISO_URLS[$CHOICE]}"
-            elif [[ "$BOOT_MODE" == "qcow2" && -n "${QCOW2_URLS[$CHOICE]}" ]]; then
-              FINAL_URL="${QCOW2_URLS[$CHOICE]}"
-            else
-              echo "::error::No valid file found for choice '$CHOICE' with boot_mode '$BOOT_MODE'"
-              exit 1
-            fi
-          else
-            echo "::error::No system_choice or source_url provided"
-            exit 1
-          fi
           
+          FINAL_URL="$USER_URL"
+          if [[ -z "$FINAL_URL" && -n "$CHOICE" ]]; then
+            if [[ "$BOOT_MODE" == "iso" ]]; then
+              FINAL_URL="${ISO_URLS[$CHOICE]}"
+            elif [[ "$BOOT_MODE" == "qcow2" ]]; then
+              FINAL_URL="${QCOW2_URLS[$CHOICE]}"
+            fi
+           
+            if [[ -z "$FINAL_URL" ]]; then
+               echo "::error::No valid URL found for choice '$CHOICE' with boot_mode '$BOOT_MODE'."
+               exit 1
+            fi
+       
+          if [[ -z "$FINAL_URL" ]]; then
+            FINAL_URL="${ISO_URLS["bliss"]}" 
+            echo "::notice::No system choice provided. Defaulting to Bliss ISO."
+          fi
+
+          echo "FINAL_SOURCE_URL=$FINAL_URL" >> $GITHUB_ENV
+
       - name: Configure VM specs
         run: |
           DISK=60
